### ISSUE TITLE
why 'start truncate iteration' in translation task?

### ISSUE THREAD

**Issue by HeegonJin** [tianjianl/error_norm_truncation#1]
I thought the strength of the method is no need to specify the starting iteration for truncation.
Is it practically better to designate a starting iteration for truncation? If then, what iteration is recommended?

Thank you for the nice work.

**Comment by tianjianl** [comment]
Thanks! The start iteration is just for experiment purposes - we varied the starting iteration for our method and found that it has minimal impact on final performance.
